services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./infra/terraform/custom-nginx/html:/usr/share/nginx/html  # Chemin corrigé

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydatabase
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
