apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      containers:
        - name: app
          image: gcr.io/votre-projet-gcp/task-manager:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: task-manager-service
spec:
  type: LoadBalancer
  selector:
    app: task-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
